apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cGFzc3dvcmQ= # Base64 encoded value of "password"
  mysql-user: cm9vdA==          # Base64 encoded value of "root"
  mysql-password: cGFzc3dvcmQ=      # Base64 encoded value of "password"
  mysql-database: ZGF0YWJhc2U=      # Base64 encoded value of "database"
