apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv2
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: wordpress-storage
  nfs:
    path: /mnt/nfs_mount
    server: 172.31.20.188
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc2
spec:
  storageClassName: wordpress-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
